# Generated by Django 5.2.8 on 2025-11-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi_laporan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('proses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga')),
            ],
        ),
    ]
