# Generated by Django 5.2.8 on 2025-11-24 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warga", "0002_pengaduan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pengaduan",
            old_name="isi_laporan",
            new_name="deskripsi",
        ),
        migrations.RenameField(
            model_name="pengaduan",
            old_name="warga",
            new_name="pelapor",
        ),
        migrations.RenameField(
            model_name="pengaduan",
            old_name="tanggal",
            new_name="tanggal_lapor",
        ),
        migrations.AddField(
            model_name="warga",
            name="tanggal_registrasi",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pengaduan",
            name="status",
            field=models.CharField(
                choices=[
                    ("BARU", "Baru"),
                    ("DIPROSES", "Diproses"),
                    ("SELESAI", "Selesai"),
                ],
                default="BARU",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="alamat",
            field=models.TextField(verbose_name="Alamat Tinggal"),
        ),
        migrations.AlterField(
            model_name="warga",
            name="nama_lengkap",
            field=models.CharField(max_length=100, verbose_name="Nama Lengkap"),
        ),
        migrations.AlterField(
            model_name="warga",
            name="nik",
            field=models.CharField(
                max_length=16, unique=True, verbose_name="Nomor Induk Kependudukan"
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="no_telepon",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Nomor Telepon"
            ),
        ),
    ]
